### ISSUE TITLE
New-TfsChangeset used in powershell script as a build step

### ISSUE THREAD

**Issue by fmanea** [Microsoft/vsts-vscode#402]
Hello,

I have a custom build step on VSTS server, in which I am using powershell to check-in a file that was modified on a previous step. the script looks like this:
``` Get-PSSnapin -Registered
Add-PSSnapin Microsoft.TeamFoundation.PowerShell
Get-TfsServer -Name "myTFSSERVER"
$rcPath = "myPathTo/File.rc"
New-TfsChangeset -Item $rcPath  -Comment "Official Build - Version : $env:Version.$env:BuildVersion" -Verbose -Override: "Build on VSTS"
```

When I build on one of my agents, I get:
```
##[error]TF10139: The following check-in policies have not been satisfied:
  Internal error in Work Items. Error loading the Work Items policy (The policy assembly 'Microsoft.TeamFoundation.VersionControl.Controls, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not registered.). Installation instructions: 
2018-05-18T11:59:56.9631091Z 
2018-05-18T11:59:56.9631091Z The policies have been overridden.
```

I can see on TFS that it does the check-in, but my PowerShell script fails (even though the check-in succeded).:

```2018-05-18T12:00:00.9991091Z ##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.
2018-05-18T12:00:01.0011091Z ##[debug]System.Exception: Process completed with exit code 0 and had 1 error(s) written to the error stream.
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShellExeHandler.<RunAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()```
```

As a consenquence of this, all my next buildsteps are not run due to this fact, Is there a way to overcome this?

Is it better to use directly the assembly instead of the cmdlet?

Best regards,
Flavian

**Comment by kaylangan** [comment]
@fmanea Are you using VS Code? This project is the for the VSTS plugin for VS Code. If you're filing an issue on VSTS/TFS, can you submit the issue on Developer Community (https://developercommunity.visualstudio.com/)?

**Comment by fmanea** [comment]
I've submitted, thanks!
